[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "dbwarden-ch-rbac"
version = "0.2.0"
description = "ClickHouse RBAC management for dbwarden"
readme = "README.md"
requires-python = ">=3.12.7"
dependencies = ["dbwarden>=0.16.0"]

[project.urls]
Homepage = "https://github.com/dbwarden-org/dbwarden-ch-rbac"
Source = "https://github.com/dbwarden-org/dbwarden-ch-rbac"

[project.entry-points."dbwarden.plugins"]
ch_rbac = "dbwarden_ch_rbac:setup"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]

[dependency-groups]
dev = [
    "pytest",
    "pytest-cov",
]
